#[test_only]
module surveysui::survey_pass_tests;

use sui::clock;
use sui::test_scenario as ts;
use surveysui::survey_pass::{Self, NullifierRegistry, IssuerConfig, SurveyPass};

const ADMIN: address = @0xA11CE;
const ALICE: address = @0xa11ce00000000000000000000000000000000000000000000000000000000000;
const BOB: address   = @0xb0b000000000000000000000000000000000000000000000000000000000000;

// Test vectors generated by scripts/gen_test_vectors.ts
fun bff_pubkey(): vector<u8> {
    vector[138, 136, 227, 221, 116, 9, 241, 149, 253, 82, 219, 45, 60, 186, 93, 114, 202, 103, 9, 191, 29, 148, 18, 27, 243, 116, 136, 1, 180, 15, 111, 92]
}

fun alice_nullifier(): vector<u8> {
    vector[2, 163, 245, 73, 111, 74, 136, 247, 122, 23, 182, 137, 34, 98, 157, 105, 176, 61, 226, 8, 176, 54, 246, 25, 252, 11, 246, 36, 69, 242, 212, 102]
}

fun alice_valid_sig(): vector<u8> {
    vector[217, 202, 151, 37, 251, 106, 24, 105, 129, 152, 219, 202, 66, 91, 132, 32, 23, 93, 16, 126, 194, 142, 232, 29, 19, 53, 115, 116, 25, 230, 43, 159, 217, 249, 13, 132, 53, 136, 248, 227, 73, 255, 171, 228, 255, 118, 116, 175, 244, 107, 131, 219, 91, 195, 171, 127, 225, 94, 27, 212, 36, 48, 155, 2]
}

fun alice_expired_sig(): vector<u8> {
    vector[64, 10, 227, 239, 31, 21, 179, 224, 91, 75, 248, 94, 255, 152, 227, 160, 155, 43, 183, 158, 136, 183, 98, 53, 96, 241, 75, 22, 215, 105, 12, 71, 93, 111, 193, 16, 213, 72, 234, 220, 111, 199, 19, 220, 83, 192, 173, 171, 26, 236, 254, 104, 118, 43, 214, 184, 225, 113, 140, 142, 41, 240, 177, 12]
}

fun bob_nullifier(): vector<u8> {
    vector[112, 207, 234, 91, 89, 165, 91, 61, 153, 163, 250, 197, 224, 231, 98, 128, 226, 27, 112, 210, 100, 132, 214, 173, 51, 120, 135, 214, 157, 161, 30, 97]
}

fun bob_valid_sig(): vector<u8> {
    vector[225, 12, 103, 172, 168, 206, 251, 66, 70, 55, 202, 241, 114, 18, 173, 161, 140, 84, 204, 69, 28, 51, 56, 35, 80, 117, 234, 196, 174, 147, 168, 41, 20, 189, 195, 238, 240, 234, 83, 154, 101, 156, 16, 9, 140, 76, 0, 214, 217, 160, 55, 231, 169, 82, 34, 78, 88, 25, 65, 127, 11, 42, 164, 11]
}

fun bob_malicious_sig(): vector<u8> {
    vector[15, 208, 62, 163, 111, 108, 180, 70, 27, 139, 54, 129, 202, 251, 236, 151, 166, 234, 108, 40, 57, 34, 236, 113, 150, 197, 254, 88, 87, 51, 103, 111, 84, 14, 94, 78, 207, 82, 104, 178, 212, 114, 34, 209, 26, 149, 138, 127, 189, 116, 206, 43, 94, 79, 40, 236, 109, 21, 141, 103, 71, 235, 130, 7]
}

const T0: u64 = 1_000_000_000;
const EXPIRES_AT: u64 = 99999999999999;

fun setup(): ts::Scenario {
    let mut sc = ts::begin(ADMIN);
    survey_pass::test_init(sc.ctx());
    sc.next_tx(ADMIN);
    {
        let mut config = ts::take_shared<IssuerConfig>(&sc);
        survey_pass::set_issuer_pubkey(&mut config, bff_pubkey(), sc.ctx());
        ts::return_shared(config);
    };
    sc.next_tx(ADMIN);
    sc
}

#[test]
fun test_surveypass_mint_happy_path() {
    let mut sc = setup();
    let mut clk = clock::create_for_testing(sc.ctx());
    clock::set_for_testing(&mut clk, T0);

    // Alice mints pass
    sc.next_tx(ALICE);
    {
        let mut registry = ts::take_shared<NullifierRegistry>(&sc);
        let config = ts::take_shared<IssuerConfig>(&sc);
        survey_pass::mint_pass(
            &mut registry,
            &config,
            ALICE,
            2, // SRC_EMAIL
            alice_nullifier(),
            vector[],
            EXPIRES_AT,
            alice_valid_sig(),
            &clk,
            sc.ctx()
        );
        ts::return_shared(config);
        ts::return_shared(registry);
    };

    sc.next_tx(ALICE);
    {
        let pass = ts::take_shared<SurveyPass>(&sc);
        assert!(survey_pass::owner(&pass) == ALICE, 1);
        assert!(survey_pass::status(&pass) == 0, 2); // STATUS_ACTIVE
        assert!(survey_pass::effective_tier(&pass) == 0, 3); // Email OTP tier is 0
        assert!(survey_pass::expires_at(&pass) == EXPIRES_AT, 4);
        assert!(survey_pass::is_valid(&pass, &clk), 5);
        ts::return_shared(pass);
    };

    clock::destroy_for_testing(clk);
    sc.end();
}

#[test, expected_failure(abort_code = surveysui::survey_pass::EDuplicateNullifier)]
fun test_surveypass_mint_rejects_duplicate_nullifier() {
    let mut sc = setup();
    let clk = clock::create_for_testing(sc.ctx());

    // Alice mints pass
    sc.next_tx(ALICE);
    {
        let mut registry = ts::take_shared<NullifierRegistry>(&sc);
        let config = ts::take_shared<IssuerConfig>(&sc);
        survey_pass::mint_pass(
            &mut registry,
            &config,
            ALICE,
            2,
            alice_nullifier(),
            vector[],
            EXPIRES_AT,
            alice_valid_sig(),
            &clk,
            sc.ctx()
        );
        ts::return_shared(config);
        ts::return_shared(registry);
    };

    // Bob tries to mint using Alice's nullifier (duplicate)
    sc.next_tx(BOB);
    {
        let mut registry = ts::take_shared<NullifierRegistry>(&sc);
        let config = ts::take_shared<IssuerConfig>(&sc);
        survey_pass::mint_pass(
            &mut registry,
            &config,
            BOB,
            2,
            alice_nullifier(),
            vector[],
            EXPIRES_AT,
            bob_malicious_sig(),
            &clk,
            sc.ctx()
        ); // must abort EDuplicateNullifier because Alice already registered it
        ts::return_shared(config);
        ts::return_shared(registry);
    };

    clock::destroy_for_testing(clk);
    sc.end();
}

#[test]
fun test_surveypass_mint_allows_update_same_owner() {
    let mut sc = setup();
    let mut clk = clock::create_for_testing(sc.ctx());
    clock::set_for_testing(&mut clk, T0);

    // Alice mints pass
    sc.next_tx(ALICE);
    {
        let mut registry = ts::take_shared<NullifierRegistry>(&sc);
        let config = ts::take_shared<IssuerConfig>(&sc);
        survey_pass::mint_pass(
            &mut registry,
            &config,
            ALICE,
            2,
            alice_nullifier(),
            vector[],
            EXPIRES_AT,
            alice_valid_sig(),
            &clk,
            sc.ctx()
        );
        ts::return_shared(config);
        ts::return_shared(registry);
    };

    // Alice updates same credential (e.g. renewal)
    sc.next_tx(ALICE);
    {
        let mut pass = ts::take_shared<SurveyPass>(&sc);
        let mut registry = ts::take_shared<NullifierRegistry>(&sc);
        let config = ts::take_shared<IssuerConfig>(&sc);
        // Alice renews with a ticket having expires_at + 1000
        survey_pass::update_pass_credential(
            &mut pass,
            &mut registry,
            &config,
            2,
            alice_nullifier(),
            vector[],
            EXPIRES_AT, // same expires_at is fine, or we can use the same valid sig
            alice_valid_sig(),
            &clk,
            sc.ctx()
        );
        ts::return_shared(config);
        ts::return_shared(registry);
        ts::return_shared(pass);
    };

    clock::destroy_for_testing(clk);
    sc.end();
}

#[test, expected_failure(abort_code = surveysui::survey_pass::EInvalidTicketSig)]
fun test_surveypass_mint_rejects_invalid_bff_sig() {
    let mut sc = setup();
    let clk = clock::create_for_testing(sc.ctx());

    sc.next_tx(ALICE);
    {
        let mut registry = ts::take_shared<NullifierRegistry>(&sc);
        let config = ts::take_shared<IssuerConfig>(&sc);
        survey_pass::mint_pass(
            &mut registry,
            &config,
            ALICE,
            2,
            alice_nullifier(),
            vector[],
            EXPIRES_AT,
            vector[0, 0, 0], // invalid sig length/content
            &clk,
            sc.ctx()
        ); // aborts on signature verification
        ts::return_shared(config);
        ts::return_shared(registry);
    };

    clock::destroy_for_testing(clk);
    sc.end();
}

#[test, expected_failure(abort_code = surveysui::survey_pass::EOwnerMismatch)]
fun test_surveypass_mint_rejects_wrong_owner() {
    let mut sc = setup();
    let clk = clock::create_for_testing(sc.ctx());

    sc.next_tx(BOB); // Bob tries to use Alice's ticket
    {
        let mut registry = ts::take_shared<NullifierRegistry>(&sc);
        let config = ts::take_shared<IssuerConfig>(&sc);
        survey_pass::mint_pass(
            &mut registry,
            &config,
            ALICE, // Alice is the owner
            2,
            alice_nullifier(),
            vector[],
            EXPIRES_AT,
            alice_valid_sig(), // Alice's sig
            &clk,
            sc.ctx()
        ); // aborts EOwnerMismatch because sender is BOB, but owner is ALICE
        ts::return_shared(config);
        ts::return_shared(registry);
    };

    clock::destroy_for_testing(clk);
    sc.end();
}

#[test, expected_failure(abort_code = surveysui::survey_pass::ETicketExpired)]
fun test_surveypass_mint_rejects_expired_ticket() {
    let mut sc = setup();
    let mut clk = clock::create_for_testing(sc.ctx());
    clock::set_for_testing(&mut clk, T0); // T0 = 1,000,000,000

    sc.next_tx(ALICE);
    {
        let mut registry = ts::take_shared<NullifierRegistry>(&sc);
        let config = ts::take_shared<IssuerConfig>(&sc);
        survey_pass::mint_pass(
            &mut registry,
            &config,
            ALICE,
            2,
            alice_nullifier(),
            vector[],
            1, // expires_at = 1 (expired)
            alice_expired_sig(),
            &clk,
            sc.ctx()
        ); // aborts on ticket expiration check
        ts::return_shared(config);
        ts::return_shared(registry);
    };

    clock::destroy_for_testing(clk);
    sc.end();
}

#[test]
fun test_surveypass_not_consumed_after_multi_survey() {
    let mut sc = setup();
    let mut clk = clock::create_for_testing(sc.ctx());
    clock::set_for_testing(&mut clk, T0);

    sc.next_tx(ALICE);
    {
        let mut registry = ts::take_shared<NullifierRegistry>(&sc);
        let config = ts::take_shared<IssuerConfig>(&sc);
        survey_pass::mint_pass(
            &mut registry,
            &config,
            ALICE,
            2,
            alice_nullifier(),
            vector[],
            EXPIRES_AT,
            alice_valid_sig(),
            &clk,
            sc.ctx()
        );
        ts::return_shared(config);
        ts::return_shared(registry);
    };

    sc.next_tx(ALICE);
    {
        let pass = ts::take_shared<SurveyPass>(&sc);
        assert!(survey_pass::is_valid(&pass, &clk), 10);
        assert!(survey_pass::is_valid(&pass, &clk), 11);
        assert!(survey_pass::is_valid(&pass, &clk), 12);
        ts::return_shared(pass);
    };

    clock::destroy_for_testing(clk);
    sc.end();
}

#[test]
fun test_surveypass_soulbound_no_store() {
    // Structural verification is code-reviewed (no store ability).
    // Test that the pass registry and config work.
    let mut sc = setup();
    sc.next_tx(ALICE);
    {
        let config = ts::take_shared<IssuerConfig>(&sc);
        assert!(survey_pass::admin(&config) == ADMIN, 20);
        ts::return_shared(config);
    };
    sc.end();
}

#[test]
fun test_surveypass_revoke_sets_revoked_status() {
    let mut sc = setup();
    let mut clk = clock::create_for_testing(sc.ctx());
    clock::set_for_testing(&mut clk, T0);

    sc.next_tx(ALICE);
    {
        let mut registry = ts::take_shared<NullifierRegistry>(&sc);
        let config = ts::take_shared<IssuerConfig>(&sc);
        survey_pass::mint_pass(
            &mut registry,
            &config,
            ALICE,
            2,
            alice_nullifier(),
            vector[],
            EXPIRES_AT,
            alice_valid_sig(),
            &clk,
            sc.ctx()
        );
        ts::return_shared(config);
        ts::return_shared(registry);
    };

    sc.next_tx(ADMIN);
    {
        let config = ts::take_shared<IssuerConfig>(&sc);
        let mut pass = ts::take_shared<SurveyPass>(&sc);
        survey_pass::revoke_pass(&mut pass, &config, sc.ctx());
        assert!(survey_pass::status(&pass) == 3, 30); // STATUS_REVOKED
        assert!(!survey_pass::is_valid(&pass, &clk), 31);
        ts::return_shared(pass);
        ts::return_shared(config);
    };

    clock::destroy_for_testing(clk);
    sc.end();
}

#[test]
fun test_surveypass_delete_after_revoke() {
    let mut sc = setup();
    let mut clk = clock::create_for_testing(sc.ctx());
    clock::set_for_testing(&mut clk, T0);

    sc.next_tx(ALICE);
    {
        let mut registry = ts::take_shared<NullifierRegistry>(&sc);
        let config = ts::take_shared<IssuerConfig>(&sc);
        survey_pass::mint_pass(
            &mut registry,
            &config,
            ALICE,
            2,
            alice_nullifier(),
            vector[],
            EXPIRES_AT,
            alice_valid_sig(),
            &clk,
            sc.ctx()
        );
        ts::return_shared(config);
        ts::return_shared(registry);
    };

    sc.next_tx(ADMIN);
    {
        let config = ts::take_shared<IssuerConfig>(&sc);
        let mut pass = ts::take_shared<SurveyPass>(&sc);
        survey_pass::revoke_pass(&mut pass, &config, sc.ctx());
        ts::return_shared(pass);
        ts::return_shared(config);
    };

    sc.next_tx(ALICE);
    {
        let pass = ts::take_shared<SurveyPass>(&sc);
        survey_pass::delete_pass(pass, sc.ctx());
    };

    clock::destroy_for_testing(clk);
    sc.end();
}
